backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "guides"
    label: "Guides"
    folder: "src/content/guides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Difficulty", name: "difficulty", widget: "select", options: ["Beginner","Intermediate","Advanced"], default: "Beginner" }
      - { label: "Est Read (min)", name: "est_read", widget: "number", required: false }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
